export const AGREGAR_PRODUCT = "AGREAR_PRODUCT";
export const AGREGAR_PRODUCT_EXITO = "AGREAR_PRODUCT_EXITO";
export const AGREGAR_PRODUCT_ERROR = "AGREAR_PRODUCT_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITO = "DESCARGA_PRODUCTO_EXITO";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTO_ERROR";

export const PRODUCTO_ELIMINAR = "PRODUCTO_ELIMINAR";
export const PRODUCTO_ELIMINAR_EXITO = "PRODUCTO_ELIMINAR_EXITO";
export const PRODUCTO_ELIMINAR_ERROR = "PRODUCTO_ELIMINAR_ERROR";
