export const AGREGAR_PRODUCT = "AGREAR_PRODUCT";
export const AGREGAR_PRODUCT_EXITO = "AGREAR_PRODUCT_EXITO";
export const AGREGAR_PRODUCT_ERROR = "AGREAR_PRODUCT_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITO = "DESCARGA_PRODUCTO_EXITO";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTO_ERROR";
